spring.application.name=payment-service

server.port=8083
logging.file.name=logs/payment-service.log

# ================= EUREKA =================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://discovery-server:8761/eureka}

# ================= KAFKA =================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# IMPORTANT FIX (optional but recommended for JSON consumers)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ================= TOPICS =================
payment.kafka.topics.booking-created=booking-created
payment.kafka.topics.payment-success=payment-success
payment.kafka.topics.payment-failed=payment-failed